nelmio_api_doc:
    documentation:
        info:
            title: API
            description: ""
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/users(?!/doc$) # Accepts routes under /api except /api/doc
