CREATE DATABASE IF NOT EXISTS `pr1`;
CREATE DATABASE IF NOT EXISTS `pr1_testing`;
GRANT ALL PRIVILEGES ON `pr1`.* TO 'pr1-user'@'%';
GRANT ALL PRIVILEGES ON `pr1_testing`.* TO 'pr1-user'@'%';
FLUSH  PRIVILEGES;